/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  StencilProps as StencilProps
} from './components/stencil-props/stencil-props';

declare global {
  interface HTMLStencilPropsElement extends StencilProps, HTMLElement {
  }
  var HTMLStencilPropsElement: {
    prototype: HTMLStencilPropsElement;
    new (): HTMLStencilPropsElement;
  };
  interface HTMLElementTagNameMap {
    "stencil-props": HTMLStencilPropsElement;
  }
  interface ElementTagNameMap {
    "stencil-props": HTMLStencilPropsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "stencil-props": JSXElements.StencilPropsAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilPropsAttributes extends HTMLAttributes {
      passInvalid?: boolean;
      showErrors?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
