/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import {
  Obj,
} from './components/my-app/my-app';

import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      arr?: number[];
      bool?: boolean;
      num?: number;
      obj?: Obj;
      str?: string;
    }
  }
}


import {
  StencilProps as StencilProps
} from './components/stencil-props/stencil-props';

declare global {
  interface HTMLStencilPropsElement extends StencilProps, HTMLElement {
  }
  var HTMLStencilPropsElement: {
    prototype: HTMLStencilPropsElement;
    new (): HTMLStencilPropsElement;
  };
  interface HTMLElementTagNameMap {
    "stencil-props": HTMLStencilPropsElement;
  }
  interface ElementTagNameMap {
    "stencil-props": HTMLStencilPropsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "stencil-props": JSXElements.StencilPropsAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilPropsAttributes extends HTMLAttributes {
      
    }
  }
}

